### ISSUE TITLE
Why JSBI is subclass of Array?

### ISSUE THREAD

**Issue by AlexMasterov** [GoogleChromeLabs/jsbi#15]
```javascript
Array.isArray(JSBI.BigInt('9007199254740992')); // true
```
This is very inconvenient for serialization libraries.
The order in which the type is determined during encoding can have a significant impact on performance. Codecs / transformers are usually used last, after `isArray` check.

**Comment by jakobkummerow** [comment]
JSBI is a subclass of Array because that's the fastest and most memory-efficient representation I could come up with. I am hesitant to compromise on those two metrics.

That said, I am interested in better understanding the problem space here. Maybe there is something else we can do to make the serialization use case more convenient.

One thing to keep in mind is the ability to transpile JSBI to native BigInts. Designing serialization support is probably particularly challenging in this regard, because a custom serializer for native BigInts will probably use `typeof o === "bigint"`, which we can't fake directly. I'm not saying that serialization-similarity to native BigInts is particularly good right now; I'm saying that if we come up with a new approach (strawman example: introduce `JSBI.prototype.SerializeMe()`), one of the most important considerations should be how it can be transpiled away -- having that migration path is more important than convenience in the short term.

**Comment by AlexMasterov** [comment]
Thanks for the reply.
