### ISSUE TITLE
SQRT

### ISSUE THREAD

**Issue by VittoriDavide** [GoogleChromeLabs/jsbi#86]
Hi is there any way to do the sort of a JSBI number?

**Comment by jakobkummerow** [comment]
There is no built-in `sqrt` function for BigInts, so JSBI (in accordance with its goal to implement the exact same behavior as native BigInts) doesn't provide one either.

That said, you can quite easily build your own. For example, you could adapt https://stackoverflow.com/questions/64190185/how-do-i-extract-the-nth-root-of-a-bigint-in-javascript to operate on JSBI values.

Of course, the mathematical square root of most integers is not an integer. Using `Numbers` is, in general, not an option because of their limited range; when returning the result as a BigInt/JSBI however, it is necessarily rounded. So, for example, `sqrt(9n) === sqrt(10n) === ... === sqrt(15n) === 3n`. 
(If you do know that `Number` range is sufficient, you can just use Numbers: `Math.sqrt(Number(2n)) == 1.4142...`; but in that case you could probably just entirely stick with Numbers and not bother with BigInts or JSBI at all, so since you do use JSBI I'm guessing this isn't your scenario.)

Depending on your use case, there may be ways to algorithmically avoid the sqrt operation. For example, instead of `if (sqrt(x) > threshold)` you could write `if (x > threshold ** 2)`.

**Comment by VittoriDavide** [comment]
Well actually I really needed the sqrt operation so I use this: 

`private sqrt(value: JSBI) {
        invariant(JSBI.greaterThan(value, ZERO), 'NEGATIVE')
        if (JSBI.lessThanOrEqual(value, TWO)) {
            return value;
        }

        function newtonIteration(n: JSBI, x0: JSBI): JSBI {
            const x1 = JSBI.signedRightShift(JSBI.add(JSBI.divide(n, x0), x0), ONE);

            if (JSBI.equal(x0, x1) || JSBI.equal(x0, JSBI.subtract(x1, ONE))) {
                return x0;
            }
            return newtonIteration(n, x1);
        }

        return newtonIteration(value, ONE);
    }`
